version: '3.7'

services:
  postgres:
    image: postgres:alpine3.19
    ports:
      - 5432:5432
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=cloud-agent
      - POSTGRES_USER=cloud-agent

  didcomm-mediator-1:
    build: .
    image: didcomm-mediator
    container_name: didcomm-mediator-1
    hostname: didcomm-mediator-1
    environment:
      #- AGENT_PUBLIC_DID=did:web:10.82.14.176%3A4000
      #- AGENT_ENDPOINTS=ws://10.82.14.176:4000
      - AGENT_NAME=2060 Cloud Agent - Dev
      - WALLET_NAME=2060-cloud-agent-dev
      - WALLET_KEY=2060-cloud-agent-dev
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=cloud-agent
      - POSTGRES_PASSWORD=cloud-agent
      - KEY_DERIVATION_METHOD=ARGON2I_MOD
      - MPR_WS_URL=ws://192.168.10.13:3100
    ports:
      - 3001:3000
      - 4001:4000
    volumes:
      - .afj:/root/.afj
    depends_on:
      - postgres
    links:
      - postgres
