version: '3.7'

services:
  postgres:
    image: postgres:alpine3.19
    ports:
      - 5432:5432
    volumes:
      - ~/data/dm/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=didcomm-mediator
      - POSTGRES_USER=didcomm-mediator

  didcomm-mediator-1:
    build: .
    image: didcomm-mediator
    container_name: didcomm-mediator-1
    hostname: didcomm-mediator-1
    environment:
      #- AGENT_PUBLIC_DID=did:web:10.82.14.176%3A4000
      #- AGENT_ENDPOINTS=ws://10.82.14.176:4000
      - AGENT_NAME=2060 DIDComm mediator - Dev
      - WALLET_NAME=2060-didcomm-mediator-dev
      - WALLET_KEY=2060-didcomm-mediator-dev
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=didcomm-mediator
      - POSTGRES_PASSWORD=didcomm-mediator
      - KEY_DERIVATION_METHOD=ARGON2I_MOD
      #- MPR_WS_URL=ws://192.168.10.13:3100
      #- MAX_RECEIVE_BYTES=1000000
      - FCM_SERVICE_BASE_URL=http://192.168.100.84:3000/test
    ports:
      - 3001:3000
      - 4001:4000
    volumes:
      - .afj:/root/.afj
    depends_on:
      - postgres
    links:
      - postgres

  didcomm-mediator-2:
    build: .
    image: didcomm-mediator
    container_name: didcomm-mediator-2
    hostname: didcomm-mediator-2
    environment:
      #- AGENT_PUBLIC_DID=did:web:10.82.14.176%3A4000
      #- AGENT_ENDPOINTS=ws://10.82.14.176:4000
      - AGENT_NAME=2060 DIDComm Mediator - Dev
      - WALLET_NAME=2060-didcomm-mediator-dev
      - WALLET_KEY=2060-didcomm-mediator-dev
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=didcomm-mediator
      - POSTGRES_PASSWORD=didcomm-mediator
      - KEY_DERIVATION_METHOD=ARGON2I_MOD
      #- MPR_WS_URL=ws://192.168.10.13:3100
      #- MAX_RECEIVE_BYTES=1000000
      - FCM_SERVICE_BASE_URL=http://192.168.100.84:3000/test
    restart: always
    ports:
      - 3002:3000
      - 4002:4000
    volumes:
      - .afj:/root/.afj
    depends_on:
      - postgres
    links:
      - postgres

  nginx:
    build: ./nginx
    ports:
      - '4000:4000'
    depends_on:
      - didcomm-mediator-1
      - didcomm-mediator-2

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
