# Base domain used for ingress host and public identifiers
global:
  domain: dev.example.io  

app:
  name: didcomm-mediator

ingress:
  enabled: true
  name: didcomm-mediator-ingress
  host: ca.{{ .Values.global.domain }}
  tlsSecret: ca.{{ .Values.global.domain }}-cert

service:
  name: didcomm-mediator-service
  ports:
    http: 80

# StatefulSet configuration (used instead of Deployment)
statefulset:
  name: didcomm-mediator
  serviceName: didcomm-mediator-service-service
  replicas: 2
  containerName: didcomm-mediator-service-container
  image:
    pullPolicy: Always
  storage: 1Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"
  env:
    AGENT_LOG_LEVEL: "0"
    AGENT_ENDPOINTS: "wss://ca.{{ .Values.global.domain }},https://ca.{{ .Values.global.domain }}"
    AGENT_NAME: "2060 Cloud Agent - dev"
    WALLET_NAME: "2060-cloud-agent-dev"
    WALLET_KEY: "2060-cloud-agent-dev"
    POSTGRES_HOST: "postgres-service-core-dev"
    POSTGRES_USER: "cloud-agent"
    POSTGRES_PASSWORD: "cloud-agent"
    AGENT_PUBLIC_DID: "did:web:ca.{{ .Values.global.domain }}"
    KEY_DERIVATION_METHOD: "ARGON2I_MOD"
    FIREBASE_CFG_FILE: /config/firebase-cfg.json
