name: Continuous Integration

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout didcomm-mediator
        uses: actions/checkout@v4

      - name: Setup Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        run: |
          npm install -g pnpm
          corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Check Format
        run: pnpm check-format

      - name: Check Types
        run: pnpm check-types

      - name: Build
        run: pnpm build
